### ISSUE TITLE
Linux binary

### ISSUE THREAD

**Issue by SkBlaz** [knutdrescher/BiofilmQ#1]
Hello! Great work on the project. Was wondering whether you could please provide also an option to run it directly for linux (e.g. ubuntu) users. Would that be possible?

Thanks!

**Comment by SkBlaz** [comment]
Thanks. Will test soon. Any way you re-build for ubuntu20 though? (should
be possible from matlab directly right?)

**Comment by erjel** [comment]
hi @SkBlaz ,

> Any way you re-build for ubuntu20 though? (should
> be possible from matlab directly right?)

re-building is not really the problem (the [build instructions](https://github.com/erjel/BiofilmQ#build-executable-for-linux) should work regardless of the distribution). Currently, the bigger problem is that I currently do not have a Ubuntu machine with Matlab Compiler at my disposal. I will ask around and see what I can do ...

**Comment by SkBlaz** [comment]
Thanks, understood, really appreciate it!

**Comment by erjel** [comment]
I re-compiled and uploaded the binary on Ubuntu. You can find it under:
https://github.com/erjel/BiofilmQ/releases/tag/v0.2.3RC1

**Comment by SkBlaz** [comment]
Awesome, thanks!
